name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build
        run: |
          yarn install --frozen-lockfile
          npx nx run-many -t dist
      - name: Archive server
        uses: actions/upload-artifact@v4
        with:
          name: dist-server
          path: |
            dist/apps/server
      - name: Archive web
        uses: actions/upload-artifact@v4
        with:
          name: dist-web
          path: |
            dist/apps/web
